runtime: nodejs
env: flex

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /logo\.svg
  static_files: static/logo.svg
  upload: static/logo\.svg

- url: /dist
  static_dir: dist

- url: /static
  static_dir: static
